### PR TITLE
`filter_nones` changed to use combinators

### PR DESCRIPTION
**Pull request by Kixunil**
This is a bit more performant thanks to collect being optimized.

### CODE REVIEW

**Comment by laanwj** [comment]
Heh, I tried this as well, but decided not to do it because the resulting code was longer instead of shorter. Especially the map to go from references to clones at the end is a bit ugly.

But if this is, even with that, more performant, sure, why not...

**Comment by Kixunil** [comment]
Finally, I'm back. :)

Ideally, there'd be draining iterator, which would allow us to get rid of the map and also avoid all those heap allocations. Maybe one day when I'm bored, I'll play with extending the API.

**Comment by laanwj** [comment]
right—seems like a good idea, but would need a change to strason, I suppose

**Comment by Kixunil** [comment]
Correct, without changing `strason`, it's impossible.

**Pull request merged**
